export const mobileDemoData = {
  company: {
    name: 'Firma demonstracyjna',
    taxId: 'XXX-XXX-XX-XX',
  },
  document: {
    id: 'zk-demo-08-2026',
    type: 'ZK',
    number: 'ZK DEMO/08/2026',
    date: '01.08.2026',
    relatedDocument: 'WZ DEMO/08/2026',
    salesDocument: 'FS DEMO/08/2026',
  },
  product: {
    id: 'net-demo-01',
    symbol: 'NET-DEMO-01',
    name: 'Router przemysłowy DEMO',
    requiredQuantity: 2,
    serialNumbers: ['SN-DEMO-2026-000123', 'SN-DEMO-2026-000124'],
  },
  documents: [
    {
      id: 'zk-demo-08-2026',
      type: 'ZK',
      number: 'ZK DEMO/08/2026',
      company: 'Firma demonstracyjna',
      progress: 0,
      required: 2,
      status: 'Do uzupełnienia',
    },
    {
      id: 'wz-demo-08-2026',
      type: 'WZ',
      number: 'WZ DEMO/08/2026',
      company: 'Klient testowy',
      progress: 3,
      required: 5,
      status: 'W trakcie',
    },
    {
      id: 'pz-demo-08-2026',
      type: 'PZ',
      number: 'PZ DEMO/08/2026',
      company: 'Dostawca demonstracyjny',
      progress: 4,
      required: 4,
      status: 'Uzupełnione',
    },
  ],
  mobileDocuments: [
    {
      id: 'zk-demo-08-2026-a',
      type: 'ZK',
      number: 'ZK DEMO/08/2026/A',
      company: 'Nordic Lab DEMO',
      taxId: 'XXX-XXX-XX-11',
      date: '01.08.2026',
      progress: 0,
      required: 2,
      status: 'Do uzupełnienia',
    },
    {
      id: 'zk-demo-08-2026-b',
      type: 'ZK',
      number: 'ZK DEMO/08/2026/B',
      company: 'Studio Magazyn DEMO',
      taxId: 'XXX-XXX-XX-22',
      date: '31.07.2026',
      progress: 1,
      required: 2,
      status: 'Do uzupełnienia',
    },
    {
      id: 'zk-demo-08-2026-c',
      type: 'ZK',
      number: 'ZK DEMO/08/2026/C',
      company: 'Testowa Sieć Północ',
      taxId: 'XXX-XXX-XX-33',
      date: '31.07.2026',
      progress: 0,
      required: 2,
      status: 'Do uzupełnienia',
    },
    {
      id: 'zk-demo-07-2026-d',
      type: 'ZK',
      number: 'ZK DEMO/07/2026/D',
      company: 'Centrum Testowe DEMO',
      taxId: 'XXX-XXX-XX-44',
      date: '30.07.2026',
      progress: 2,
      required: 2,
      status: 'Uzupełnione',
    },
    {
      id: 'zk-demo-07-2026-e',
      type: 'ZK',
      number: 'ZK DEMO/07/2026/E',
      company: 'Pracownia Logistyki DEMO',
      taxId: 'XXX-XXX-XX-55',
      date: '29.07.2026',
      progress: 1,
      required: 1,
      status: 'Uzupełnione',
    },
    {
      id: 'pz-demo-08-2026-a',
      type: 'PZ',
      number: 'PZ DEMO/08/2026/A',
      company: 'Dostawca Testowy Alfa',
      taxId: 'XXX-XXX-XX-61',
      date: '01.08.2026',
      progress: 0,
      required: 2,
      status: 'Do uzupełnienia',
    },
    {
      id: 'pz-demo-07-2026-b',
      type: 'PZ',
      number: 'PZ DEMO/07/2026/B',
      company: 'Hurtownia Fikcyjna DEMO',
      taxId: 'XXX-XXX-XX-62',
      date: '30.07.2026',
      progress: 2,
      required: 2,
      status: 'Uzupełnione',
    },
    {
      id: 'wz-demo-08-2026-a',
      type: 'WZ',
      number: 'WZ DEMO/08/2026/A',
      company: 'Odbiorca Techniczny DEMO',
      taxId: 'XXX-XXX-XX-71',
      date: '01.08.2026',
      progress: 1,
      required: 2,
      status: 'Do uzupełnienia',
    },
    {
      id: 'wz-demo-07-2026-b',
      type: 'WZ',
      number: 'WZ DEMO/07/2026/B',
      company: 'Salon Pokazowy DEMO',
      taxId: 'XXX-XXX-XX-72',
      date: '30.07.2026',
      progress: 2,
      required: 2,
      status: 'Uzupełnione',
    },
  ],
  pickingStates: [
    {
      pickedQuantity: 0,
      status: 'Do zebrania',
      message: 'Zeskanuj pierwszy produkt',
    },
    {
      pickedQuantity: 1,
      status: 'Częściowo',
      message: 'Zebrano pierwszą sztukę',
    },
    {
      pickedQuantity: 2,
      status: 'Zebrane',
      message: 'Pozycja jest kompletna',
    },
  ],
  scanner: {
    formats: ['Code 128', 'Code 39', 'EAN', 'UPC', 'QR'],
    singleModeLabel: 'Pojedynczy',
    seriesModeLabel: 'Seryjny',
    narrowTargetLabel: 'Wąski celownik',
    fullTargetLabel: 'Pełny kadr',
  },
}
